name: CrazyShopZ
version: '1.0.0'
main: me.devallenalt_tw.crazyshopz.CrazyShopZ
api-version: '1.21'
author: Dev_Allenalt_tw
description: Advanced shop plugin for Minecraft
website: https://github.com/Dev_Allenalt_tw/CrazyShopZ

depend:
  - PlaceholderAPI
  - Vault
  - LuckPerms

commands:
  shop:
    description: Opens the shop GUI
    usage: /shop [category]
    permission: crazyshopz.use
  sellgui:
    description: Opens the selling GUI
    usage: /sellgui
    permission: crazyshopz.sell

permissions:
  crazyshopz.use:
    description: Allows access to shop command
    default: true
  crazyshopz.sell:
    description: Allows access to sell GUI
    default: true
  crazyshopz.admin:
    description: Admin permissions for CrazyShopZ
    default: op
